# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'
  # If you targeting iOS
target 'OurQueue' do
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for OurQueue
  pod 'Spartan'

end
